export const elements = {
  serviceStatus: document.getElementById("serviceStatus"),
  pingButton: document.getElementById("pingButton"),
  workspaceTabButtons: document.querySelectorAll('[data-tab-group="workspace"][data-tab]'),
  workspaceTabPanels: document.querySelectorAll('[data-tab-group="workspace"][data-tab-panel]'),
  transactionTabButtons: document.querySelectorAll('[data-tab-group="transactions"][data-tab]'),
  transactionTabPanels: document.querySelectorAll('[data-tab-group="transactions"][data-tab-panel]'),
  accountForm: document.getElementById("accountForm"),
  accountOutput: document.getElementById("accountOutput"),
  paymentForm: document.getElementById("paymentForm"),
  paymentOutput: document.getElementById("paymentOutput"),
  transactionListForm: document.getElementById("transactionListForm"),
  transactionListOutput: document.getElementById("transactionListOutput"),
  transactionLookupForm: document.getElementById("transactionLookupForm"),
  transactionLookupOutput: document.getElementById("transactionLookupOutput"),
};
